### ISSUE TITLE
Preguntas Frecuentes I2

### ISSUE THREAD

**Issue by CarloGauss33** [IIC2133-PUC/2021-2#108]
## Pregunta 0

-  ¿Donde se incluye la P0?
>Puede ser en la primera página de la P1 o de la P2

-  ¿Qué ocurre si olvido responder la P0?
>Tu prueba puede no ser revisada, o en el caso de ser corregida se aplicará un descuento alto

- ¿La P0 debe ser en papel?
> Siempre y cuando se aprecie que la firma es tuya, puedes utilizar cualquier medio para escribirla

## Pregunta 1
- ¿Que es el query?
> Dado el rango (a, b) nos da cual es el k-esimo menor

-  Cuando dicen que la estructura de datos se tiene que crear linealmente, eso es sin contar los add(x) verdad? Osea los add pueden tener mayor complejidad?
> Si, se refiere a crear una estructura vacia

- ¿La complejidad de que depende?
> Solo del rango

- Se parte sin datos
> Si

- ¿Si agrego el mismo número muchas veces, se guardan las repeticiones?
> Si, guardo los elementos repetidos.

- ¿Debo preocuparme del manejo de errores ? (query siempre entregue algo valido)
> No es necesario, pero puedes hacerlo.

## Pregunta 2
- ¿Debemos escribir el algoritmo o describirlo?
>Se debe dar una secuencia de pasos un algoritmo o pseudocódigo. Lo importante es que quede muy claro cómo se va desarrollando la idea.

- La lista T tiene cuántos valores?
> Tiene n elementos

- El algoritmo es un lenguaje o formato específico?
> No, basta con que sea una descripción de alto nivel, pero que sea entendible

- ¿La lista D tiene algún orden de como están registrados los valores?
> La lista D está ordenada con el valor de las diferencias. (siguiendo de menor -> mayor)

- Pueden existir diferencias de tiempo repetidas?
> Si

- Pueden existir tiempos repetidos en la lista T para la pregunta 2?
> Si aunque no es relevante

## Pregunta 3
- ¿En la a basta con dibujar el árbol?
> Si pero es recomendable que dibujen paso a paso para prevenir errores

- ¿En la B, el numero de alumno tiene algun formato en especifico?
> El mismo formato de cualquier alumno de la universidad

## Pregunta 4

- La parte a y b valen 0 puntos
> Si

- Se debe demostrar la complejidad, o basta con justificar
> Mientras quede bien claro como se concluye la justificacion esta todo OK

## Otros

- O(n) > O(log^2(n))
> Si

**Comment by CarloGauss33** [comment]
Pueden hacer preguntas vía comentarios tambien si es que su pregunta no se encuentra en las comunes

**Comment by tamarabend** [comment]
Hola! Para la pregunta 3, se puede asumir que no existen números de alumno terminados en J o es necesario que consideremos eso?

**Comment by veneguitas** [comment]
Para cualquier pregunta, en vez de hacerlo con pseudocódigo, puedo escribir el código en C? Me parece que escuché al profe decir que si, pero quiero confirmar

**Comment by CarloGauss33** [comment]
> Hola! Para la pregunta 3, se puede asumir que no existen números de alumno terminados en J o es necesario que consideremos eso?

@tamarabend Los alumnos terminados en J si existen, aunque puedes decir que los mapeas a otro numero y asi solucionas tu problema. Igualmente podrías llegar a asumir lo que deseas, aunque tienes que explicitar esto en tu interrogación

**Comment by CarloGauss33** [comment]
> Para cualquier pregunta, en vez de hacerlo con pseudocódigo, puedo escribir el código en C? Me parece que escuché al profe decir que si, pero quiero confirmar

@veneguitas Si se puede, idealmente que quede bien legible y claro para el momento de la correccion

**Comment by fran-gl** [comment]
Hola! Se pueden escribir las respuestas en word y luego pasarlo a pdf?

**Comment by etoteiza** [comment]
Hola! 
Para la pregunta 2, si bien la lista D está ordenado de menor a mayor. Puedo decir que es, en orden, la diferencia entre corredor 1 y 2, corredor 2 y 3, y así?

**Comment by CarloGauss33** [comment]
> Hola! Se pueden escribir las respuestas en word y luego pasarlo a pdf?

@fran-gl Si, se puede

**Comment by CarloGauss33** [comment]
> Hola! Para la pregunta 2, si bien la lista D está ordenado de menor a mayor. Puedo decir que es, en orden, la diferencia entre corredor 1 y 2, corredor 2 y 3, y así?

@etoteiza No, el orden es global. Osea puede que una diferencia corresponda a 1,2 y la segunda corresponda a la 3,7

**Comment by vsmatthews** [comment]
Hola! Para la pregunta 2 si es q hay mas de una solucion se entrega la primera q se encuentra?

**Comment by ticastro** [comment]
Para la 3a, que el max-heap este desbalanceado significa que no necesariamente debe tener todas sus hojas en el nivel h o h-1 ?

**Comment by rmena1** [comment]
Hola! puede ser que en la pregunta 2 puede haber más de una lista T para una lista D? Por ejemplo, para la lista T de ejemplo del enunciado [0, 40, 65, 110] la lista D es [25, 40, 45, 65, 70, 110], pero para la lista T' = [0, 45, 70, 110] la lista D' asociada también es [25, 40, 45, 65, 70, 110]. 

Por lo tanto nuestro algoritmo podría devolver T o T' para la lista de input D. Esto es correcto o hay alguna consideración que no estoy tomando en cuenta?

**Comment by CarloGauss33** [comment]
> Hola! Para la pregunta 2 si es q hay mas de una solucion se entrega la primera q se encuentra?

@vsmatthews Si, la primera que encuentren

**Comment by Coolgatty** [comment]
Hola, me di cuenta de que si tomamos la lista T = [0, 15, 34, 46] la cual produce una lista D = [12, 15, 19, 31, 34, 46] entonces si luego reconstruimos la lista T a partir de D nos puede dar 2 resultados diferentes pero ambos validos segun las condiciones del problema. Obviamente solo una de ellas es la correcta pero a partir de D no tenemos la informacion suficiente para hacer esto diferencia. Esto sera un problema? O estoy yo equivocado y me falta pensar en algo?

T1 = [0, 15, 34, 46]
T2 = [0, 12, 31, 46]

**Comment by etoteiza** [comment]
Para la pregunta 2 ya se conoce D, se puede asumir N conocido también?

**Comment by CarloGauss33** [comment]
> Hola, me di cuenta de que si tomamos la lista T = [0, 15, 34, 46] la cual produce una lista D = [12, 15, 19, 31, 34, 46] entonces si luego reconstruimos la lista T a partir de D nos puede dar 2 resultados diferentes pero ambos validos segun las condiciones del problema. Obviamente solo una de ellas es la correcta pero a partir de D no tenemos la informacion suficiente para hacer esto diferencia. Esto sera un problema? O estoy yo equivocado y me falta pensar en algo?
> 
> T1 = [0, 15, 34, 46] T2 = [0, 12, 31, 46]

@Coolgatty Se solicita solo la primera configuracion valida, por lo que si puede ocurrir

**Comment by domingo2000** [comment]
Si en alguna pregunta quiero implementar una tabla de hash, debo describir la función de hash a utilizar, o basta con decir que se tiene una función de hash buena de antemano?

**Comment by JuaniAndres** [comment]
Hola, en la pregunta 1 puedo asumir que todas las consultas query van a poder retornar un valor en base a las variables entregadas?

**Comment by JoMarchant** [comment]
Holaa, ¿en la pregunta 1 se espera que se maneje un número infinito de consultas?

**Comment by baosse** [comment]
Holaa, en la 2, la función de backtracking debe recibir solo la lista D o puede recibir más parámetros?

**Comment by nicoparraguez** [comment]
Me uno a domingo2000, ahí que mostrar la función de hash o basta con decir que se tiene una buena?

**Comment by macavarelau** [comment]
Tengo varias preguntas:
- [2] Se asume que D tendrá un largo tal que se pueda obtener fácilmente el largo de T?
- [3.a] Hay múltiples soluciones para la construcción del árbol?
- [3.b] Me uno a la pregunta de Domingo, se obvia la parte de la función de hash, o hay que explicitarla?

**Comment by jaimecoloma** [comment]
Hola! Respecto a la 3.b debo utilizar mi edd para un algoritmo que me permita saber los k estudiantes con más votos en el momento? Que no quedé seguro de si basta solamente con describir la estructura de datos utilzada.

**Comment by vicho-muon** [comment]
Holaa
Si en la 1 se indica que la complejidad sólo depende del rango, entonces cuando nos dicen que debe ser menor que O(log^2(n)), ese n es el tamaño del rango?

**Comment by CarloGauss33** [comment]
> función de hash a utilizar, o basta con decir que se tiene una función de hash buena de antemano?

Deberias describir al menos a grandes rasgos como funcionaria la funcion de hash

**Comment by CarloGauss33** [comment]
> Hola! Respecto a la 3.b debo utilizar mi edd para un algoritmo que me permita saber los k estudiantes con más votos en el momento? Que no quedé seguro de si basta solamente con describir la estructura de datos utilzada y relacionarlo a la votación nomas.

Debes describir la estructura y explicar como funcionaria para obtener dichos K estudiantes

**Comment by CarloGauss33** [comment]
> Holaa Si en la 1 se indica que la complejidad sólo depende del rango, entonces cuando nos dicen que debe ser menor que O(log^2(n)), ese n es el tamaño del rango?

Correcto

**Comment by vicentesh** [comment]
Hola, para la pregunta 1 add(x) tambien debe ser O(log^2(n)) o se refiere solo a la query?

**Comment by etoteiza** [comment]
En la 3a es necesario un pseudocódigo o puedo ir explicando a medida que lo armo?

**Comment by CarloGauss33** [comment]
> Hola! Tengo varias preguntas:
> 
> * [2] Se asume que D tendrá un largo tal que se pueda obtener fácilmente el largo de T?
> * [3.a] Hay múltiples soluciones para la construcción del árbol?
> * [3.b] Me uno a la pregunta de Domingo, se obvia la parte de la función de hash, o hay que explicitarla?

2 No entiendo a que te refieres con obtener el largo de D a partir de T
3b. No es nescesario explicitarla pero al menos deben mencionar como funcionaria la "traduccion" hacia la tabla de hash

**Comment by CarloGauss33** [comment]
> En la 3a es necesario un pseudocódigo o puedo ir explicando a medida que lo armo?

Puedes ir explicando a medida que lo armas siempre y cuando la explicacion sea clara y detallada

**Comment by CarloGauss33** [comment]
> Holaa, ¿en la pregunta 1 se espera que se maneje un número infinito de consultas?

No infinito, pero si un numero arbitrariamente grande de consultas

**Comment by CarloGauss33** [comment]
> Holaa, en la 2, la función de backtracking debe recibir solo la lista D o puede recibir más parámetros?

Cualquier parametro siempre y cuando tenga sentido y este bien argumentado

**Comment by gianlucafalcone** [comment]
Hola, para la pregunta 2, se supone que perdemos  la lista T pero nosotros conocemos los valores que estaban en ella? o al perder la lista estos tambien se olvidan?

**Comment by Viperez6** [comment]
Hola! en la 2 se puede asumir que dos corredores no llegaran al mismo tiempo? es otras palabras que en T no habrían elementos duplicados?

**Comment by vsmatthews** [comment]
acabo de leer en preguntas anteriores sobre la 3a, el enunciado en ningun momento dice que hay q explicar la construccion del arbol ni hacer un pseudocodigo solo sale dibuja el arbol. Entonces al final si hay q explicar como lo hice??

**Comment by mc-cari** [comment]
Hola, en la pregunta 4, x es parte del árbol final?

**Comment by nicoparraguez** [comment]
Tengo una duda en la 3a, hasta que punto hay que ser exhaustivo con el algoritmo para colocar los nodos? o basta con dibujar y que cumpla ambos requerimientos de ser un ABB y max heap?

**Comment by DomingoCarvajal** [comment]
Hola! En la pregunta 4.d los nodos tienen el inidcador de -1/0/1 dependiendo de si estan levemente desbalanceados o no?

**Comment by CarloGauss33** [comment]
> Hola! En la pregunta 4.d los nodos tienen el indicador de -1/0/1 dependiendo de si están levemente desbalanceados o no?

Si, debe ir ahi. Tambien puedes suponer que cada nodo tiene su altura

**Comment by CarloGauss33** [comment]
> acabo de leer en preguntas anteriores sobre la 3a, el enunciado en ningun momento dice que hay q explicar la construccion del arbol ni hacer un pseudocodigo solo sale dibuja el arbol. Entonces al final si hay q explicar como lo hice??

Basta con dibujarlo paso a paso, la explicacion es mas que nada para que entendamos mejor la respuesta al momento de corregir

**Comment by Coolgatty** [comment]
Encuentro que pedir algo por aca que no se pide en el enunciado es medio raro. Yo termine hace rato y no estoy en mi casa (me organice para terminar temprano) y recien me entero que estan pidiendo que se dibuje paso a paso en la 3a que no se pide en el enunciado. Me bajaran por no hacerlo paso a paso?

**Comment by CarloGauss33** [comment]
> Encuentro que pedir algo por aca que no se pide en el enunciado es medio raro. Yo termine hace rato y no estoy en mi casa (me organice para terminar temprano) y recien me entero que estan pidiendo que se dibuje paso a paso en la 3a que no se pide en el enunciado. Me bajaran por no hacerlo paso a paso?

No se pide paso a paso. Solo es recomendable para así obtener puntajes parciales en caso de error.

**Comment by Coolgatty** [comment]
> > Encuentro que pedir algo por aca que no se pide en el enunciado es medio raro. Yo termine hace rato y no estoy en mi casa (me organice para terminar temprano) y recien me entero que estan pidiendo que se dibuje paso a paso en la 3a que no se pide en el enunciado. Me bajaran por no hacerlo paso a paso?
> 
> No se pide paso a paso. Solo es recomendable para así obtener puntajes parciales en caso de error.

Ok gracias por la aclaracion!

**Comment by CarloGauss33** [comment]
> Si quiero describir algún algoritmo tiene que ser pensando en c o puede ser en python por ejemplo ??

No, basta con que sea pseudocodigo o simplemente una descripcion de como funciona. Lo importante es que quede claro

**Comment by DomingoCarvajal** [comment]
Hola! Sorry por no preguntar esto en el zoom. Pero no cacho bien a que se refiere la 4.e. Que 3 partes hay que unir?

**Comment by itplanella** [comment]
Hola, en la pregunta 1, el add(x) tambien debe tener complejidad de a lo mas 𝑂(log2 𝑛), o solo se exige para el query?

**Comment by Sadhguy** [comment]
Hola, para la 3b podemos asumir que los números de alumno son secuenciales?

**Comment by fran-gl** [comment]
Hola, en la pregunta 1, la consulta add() debe retornar algo o solo agregar el dato a la estructura?

**Comment by antonia-reyes** [comment]
holaaaa, se puede hacer la i escrita a mano y después subirla en pdf escaneada?

**Comment by DomingoCarvajal** [comment]
Hola! Podemos asumir que el "k" es relativamente pequeño? 

Me imagino que k no es tan grande por lo que si hago operaciones O(k) no debería ser tan ineficiente.

**Comment by maggiemunoz** [comment]
Para la 4 los algoritmos deben estar en pseudocodigo o pueden ser explicados nomás?

**Comment by CarloGauss33** [comment]
> holaaaa, se puede hacer la i escrita a mano y después subirla en pdf escaneada?

Siempre y cuando quede ordenado, Si

**Comment by CarloGauss33** [comment]
> Hola! Podemos asumir que el "k" es relativamente pequeño?
> 
> Me imagino que k no es tan grande por lo que si hago operaciones O(k) no debería ser tan ineficiente.

Si, igualmente cualquier cosa que asumas tienes que explicitarlo

**Comment by CarloGauss33** [comment]
> Para la 4 los algoritmos deben estar en pseudocodigo o pueden ser explicados nomás?

Pueden ir de cualquier forma siempre y cuando quede clara la explicación y el funcionamiento.

**Comment by maggiemunoz** [comment]
> > Para la 4 los algoritmos deben estar en pseudocodigo o pueden ser explicados nomás?
> 
> Pueden ir de cualquier forma siempre y cuando quede clara la explicación y el funcionamiento.

Gracias!

**Comment by RonaldoSosa** [comment]
Para la 3b se debe calcular complejidad?

**Comment by mariajoseguerrero** [comment]
Hola! En la 1 no sabemos el valor de n?

**Comment by CarloGauss33** [comment]
> Para la 3b se debe calcular complejidad?

No es nescesario

**Comment by CarloGauss33** [comment]
> Hola! En la 1 no sabemos el valor de n?

Con valor de n te refieres al rango?

**Comment by BenjaRubio** [comment]
Hola! En la 4e, dado que no se especifica nada sobre las alturas de A y B, cuando dice que debe demorarse O(log n), ese n sería el número de nodos del árbol más chico, más grande, o que?

**Comment by mariajoseguerrero** [comment]
> > Hola! En la 1 no sabemos el valor de n?
> 
> Con valor de n te refieres al rango?

Si! Me refiero si al comenzar sabemos el valor del rango

**Comment by vicentevegaulloa** [comment]
Hola! Puedo no demostrar la complejidad de un algoritmo que se vió en clases? Decir algo como: "Esto es O(algo) como se dijo en la clase X"
