### ISSUE TITLE
[I2] Multiples resultados en la Pregunta 2

### ISSUE THREAD

**Issue by Coolgatty** [IIC2133-PUC/2021-2#109]
Hola, me di cuenta de que si tomamos la lista T = [0, 15, 34, 46] la cual produce una lista D = [12, 15, 19, 31, 34, 46] entonces si luego reconstruimos la lista T a partir de D nos puede dar 2 resultados diferentes pero ambos validos segun las condiciones del problema. Obviamente solo una de ellas es la correcta pero a partir de D no tenemos la informacion suficiente para hacer esto diferencia. Esto sera un problema? O estoy yo equivocado y me falta pensar en algo?

T1 =  [0, 15, 34, 46] 
T2 = [0, 12, 31, 46]

**Comment by yadran** [comment]
Creo que sí es posible.
Una solución es que tu algoritmo genere todas las listas válidas posibles;
otra, que simplemente genere la primera.  Ve tú.
En cualquier caso, lo importante es que tu respuesta deje claro que
entiendes cómo funciona backtracking.
--Yadran
