### ISSUE TITLE
Tarea 3 - Dudas varias

### ISSUE THREAD

**Issue by nicolascuevas1** [IIC2133-PUC/2021-2#112]
Hola, tengo un par de dudas con respecto a la tarea 3:
              - Si se optara a sólo realizar el MST en la parte 1, ¿El formato de output es el mismo que si lo hicieramos completo? Es decir, incluir los puntos del MST junto con la cantidad de edges al principio.
              - Para la parte 2, ¿el archivo costs_lights.json que subieron está bien?, para el test easy_0, por ejemplo, el costo indicado es N - 1, donde N es el largo de la recta. Pregunto ya que esto es hacer una conexión simple entre los nodos sin ninguna restricción.
              - Al parecer las distintas ramas del servidor no están funcionando, ¿las habilitarán durante la semana?
Saludos y gracias de antemano

**Comment by CarloGauss33** [comment]
1. Si
2. Eso aun esta siendo revisado, durante hoy y mañana daremos datos concretos
3. Solo esta funcionando la correccion de la parte 1, la parte 2 aun no esta habilitada o te refieres a otra cosa?

**Comment by nicolascuevas1** [comment]
Con lo del servidor, me refiero a que cuando intento usar la test branch, me arroja el siguiente mensaje:
 
Repo: T3-2021-2-nicolascuevas1
Branch: test
Rama inexistente.

**Comment by CarloGauss33** [comment]
Revisando tu git, no veo que tengas mas de 1 brach. Probablemente el push quedo incompleto

**Comment by nicolascuevas1** [comment]
Lo revisaré, gracias por las respuestas
