### ISSUE TITLE
id pasajeros Tarea 0

### ISSUE THREAD

**Issue by domingo2000** [IIC2133-PUC/2021-2#12]
Hola, leyendo el enunciado tengo la duda de si los ids de los pasajeros (Magos o comerciaggles) son unicos o no, puesto que dice "Para identificar a los pasajeros, estos tendran un id que consiste en un entero que parte en 0 y crece a medida que llega un nuevo pasajero". Entonces pueden pasajeros de distintas estaciones tener el mismo id??. 
Ejemplo:
PASAJERO estacion_0, anden, destino, categoria -> id del pasajero = 0 por ser el primero
PASAJERO estacion_1, anden, destino, categoria -> id del pasajero = ¿?
deberia ser 0 por ser el primero, o 1 por ser el segundo pasajero generado en el programa??

**Comment by chineseJack564** [comment]
Hola, los ids de pasajero son únicos entre todas las estaciones! Entonces debes tener un contador de id para todos los pasajeros!
