### ISSUE TITLE
Problema con VirtualBox en Mac

### ISSUE THREAD

**Issue by Sadhguy** [IIC2133-PUC/2021-2#13]
He seguido todos los pasos de la guía de instalación, pero al tratar de iniciar la instalación de Ubuntu me arroja el siguiente error:

The virtual machine 'Ubuntu' has terminated unexpectedly during startup with exit code 1 (0x1).
Código resultado: | NS_ERROR_FAILURE (0x80004005)

No se como puedo solucionar este problema, busque en google pero ninguna de las soluciones planteadas me sirvió.

**Comment by FdoTorres1** [comment]
Hola!

Encontré este [link](https://apple.stackexchange.com/questions/408154/macos-big-sur-virtualbox-error-the-virtual-machine-has-terminated-unexpectedly-d) donde se resuelve un problema con el mismo código de error, quizás te podría servir.

**Comment by Sadhguy** [comment]
Hola, lo revisé y no me funcionó. Hay alguien que pueda ayudarme directamente para no retrasarme con la tarea? D: Busque mucha info del problema y no he podido solucionarlo. Igual agradezco el link

**Comment by CarloGauss33** [comment]
Hola @Sadhguy, Habla por el Discord del curso para que así algun ayudante pueda ver tu caso mas a detalle. Igualmente si la maquina virtual no funciona agregamos una guia de como utilizar C y Valgrind con Docker

https://discord.gg/cHM46t8t
