### ISSUE TITLE
Error al clonar repo en mi pc

### ISSUE THREAD

**Issue by ian-fell** [IIC2133-PUC/2021-2#15]
Hola! 
Hoy empezé a revisar la tarea con la intención de comenzar, y al intentar clonar el repo como siempre lo hago, esta vez como nunca me pide mi identificación para poder clonar. Ingreso mis datos, y al poner aceptar, me arroja el siguiente error

<img width="566" alt="Error al clonar" src="https://user-images.githubusercontent.com/62180167/131228553-2a8888d4-b7cb-4cd9-8638-e9a4f4af7565.png">

No me había pasado nunca antes y no se como solucionarlo :(

**Comment by CarloGauss33** [comment]
Hola Ian, lo que ocurre es que Github modifico sus politicas de seguridad, por lo que no basta con logearse con contraseña. Tienes que utilizar un Personal Access Token. 
En este link encuentras mas informacion

[PAT Github](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token)
