### ISSUE TITLE
[Tarea 0] Fila de pasajeros en el andén

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2133-PUC/2021-2#17]
Hola! Tengo una duda con esta parte del enunciado, estoy confundido con la parte que dice: "En otro caso el pasajero se ubica al final de la fila de su categoría", eso significa que habrá dos filas, una para los que tienen pasajes Premium y otra para los que tienen pasajes Normal, o solo habrá una fila, en caso de ser solo una fila me surge otra duda en las imágenes de esta parte del enunciado se ve que cuando llega un pasajero con pasaje Premium y no hay un tren se coloca por delante del pasajero que tenía pasaje Normal  que estaba antes en la fila, no debería de colocarse al último por lo dicho en el enunciado?
![Captura de pantalla (183)](https://user-images.githubusercontent.com/62029138/131238312-953cd567-a5e4-4092-8955-202aef226bb5.png)

**Comment by TrinidadVargas** [comment]
Hola! Puedes modelar el problema como prefieras (si usar una fila o dos) Lo importante es que al imprimir la fila los pasajeros premium siempre estarán antes que los normales. Y el orden dentro de los pasajeros premium es por orden de llegada, igual que el orden dentro de los pasajeros normales.

Si lo haces con una fila, al llegar un pasajero premium se ubicará después del último pasajero premium y antes del primer pasajero normal. Si llega un pasajero normal se ubica después del último pasajero normal

**Comment by RonaldoSosa** [comment]
Entendido! Gracias :) !!!!
