### ISSUE TITLE
[Tarea 0] Evento remover

### ISSUE THREAD

**Issue by trinidadgatica** [IIC2133-PUC/2021-2#18]
Hola!, 

Cuando en el main reciben los datos usar el id de la estación y del anden, además de "car", y del asiento, con "car" ¿se refieren al tren o al vagón?

**Comment by nfragav** [comment]
Hola! Se refiere al vagón. Dado que el tren estará parado en la estación y andenes en específico, puedes asumir que no necesitas información de qué tren es, y que al dirigirte a una estación y andén dados, removerás al pasajero antes de que el tren parta de allí.
