### ISSUE TITLE
Cantidad pasajeros fila anden

### ISSUE THREAD

**Issue by domingo2000** [IIC2133-PUC/2021-2#19]
Hola, quería preguntar si es que la cantidad de pasajeros que acepta la fila del anden es finita (EJ: caben máximo 100 pasajeros en la fila), o es variable y podrían llegar miles de pasajeros a una sola fila??.

**Comment by nfragav** [comment]
Hola! El largo de las filas es variable y podrían llegar a miles en una sola fila. Tu programa debería poder permitir esto. Te recomiendo aplicar distintas estructuras de datos para modelar este aspecto como otros requerimientos de la tarea.
