### ISSUE TITLE
Tests Tarea 0

### ISSUE THREAD

**Issue by TrinidadVargas** [IIC2133-PUC/2021-2#20]
## Tests Tarea 0

Puedes descargar los tests y las soluciones [acá](https://drive.google.com/drive/folders/170WiqFRHiutxfRMNTOhXwS-FbmDsEiYI?usp=sharing).

Los tests se dividen en tres dificultades: easy, medium y hard donde los tests easy y medium buscan evaluar la correctitud del programa y los tests hard buscan evaluar eficiencia. Cada dificultad tiene el mismo valor en la nota. Los tests publicados **NO** serán los mismos que los de evaluación, pero tendrán las mismas características.

Para correr los tests debes usar el siguiente comando
```./magictrains tests/easy/test_0.txt out.txt```
y debe dar un resultado en **menos de 10 segundos**

Luego, para comparar que esté correcto puedes usar el siguiente comando en la terminal
```diff -b out.txt solutions/easy/out_0.txt```

Si el output de diff es vacío, entonces los resultados son iguales y tendrás el puntaje en el test, de lo contrario te mostrará las líneas que son distintas para que puedas debuguear.

En esta tarea, para que la nota sea gradual no se incluyó todos los eventos en todos los tests. A continuación se menciona los eventos que incluye cada test.

Easy
test 0: Pasajero y Estación
test 1:  Pasajero, Estación, Nuevo Tren, Remover
test 2: Pasajero, Estación, Nuevo Tren, Salir, Llegar, Desaparecer
test 3: Pasajero, Estación, Nuevo Tren, Salir, Separar

Medium y Hard
test 0: Pasajero y Estación
test 1: Pasajero, Estación, Nuevo Tren, Remover
test 2: Pasajero, Estación, Nuevo Tren, Remover, Salir, Llegar, Desaparecer
test 3: Todos

**Comment by bpeirano1** [comment]
Hola @TrinidadVargas ! Es posible que creen un test medium con solución de Pasajero, Estación, Nuevo Tren para poder debuggear los problemas entre subir pasajeros y bajar pasajeros?

Saludos y gracias!

**Comment by Coolgatty** [comment]
Hola tengo un problema. Creo que los tests estan malos pero podria ser problema mio. En el test easy/test_1.txt por ejemplo se crea solo 1 pasajero premium para el tren 3 (NUEVO-TREN 1 0 1 4) luego se pide remover el pasajero en el vagon 0 y asiento 1 (REMOVER 1 0 0 1) entremedio no hay ningun SALIR por lo que no pueden haber pasajeros normales en el tren y por lo tanto el asiento 1 del vagon 0 esta vacio. Por favor me pueden confirmar si esto esta mal? 

Ademas en el output del test_1 de easy sale  que se removio un pasajero con id 15 el cual es un pasajero normal y como no hay ningun comando SALIR entonces no es posible que  haya un pasajero normal en un tren. Estoy en lo correcto?

Esto ocurre en los otros tests tambien en donde se ejecuta REMOVER a un asiento que esta vacio.

**Comment by burgosibarra** [comment]
Hola! Los problemas hard también deben terminar en 10s? 😨
