### ISSUE TITLE
[Tarea 0] No sé cómo partir la tarea

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2133-PUC/2021-2#27]
Hola, sorry por lo perdido, no estoy muy familiarizado con C y todavía estoy estancado tratando de averiguar como empezar a codificar. Ya me vi los videos de intro a C y lei el enunciado, y si bien siento tener una buena idea de cómo simular los trenes de DCCwarts usando OOP, y gracias a los videos tengo una idea de cómo hacerlo mediante structs y funciones en lenguaje C, me pasa que al ver el main.c y los espacios [Por implementar] del código no entiendo bien dónde definir los structs y las funciones específicas de los structs. Agradecería cualquier orientación respecto al tema.

Desde ya gracias.

**Comment by Huasito-Appel** [comment]
Hola Juan, no te preocupes yo anduve igual al comienzo.
Lo mas importante es tener un esquema mental de como abordar la tarea, ver que estructuras usaremos para modelar a los distintos agentes, como los trenes.
Quizas una buena forma de iniciar seria tener un archivo .c , aparte, en donde modeles estas structs e implementes un par de eventos como funciones para ir agarrando mas confianza, no te preocupes de que sea tal y como dice el enunciado, familiarizate con el uso de punteros.
Exito en tu tarea :smiley:

**Comment by JuanpaBC** [comment]
Yapo seguiré tu consejo, muchas gracias!
