### ISSUE TITLE
Valgrind

### ISSUE THREAD

**Issue by PedroFuenzalida** [IIC2133-PUC/2021-2#39]
Hola! Al ejecutar "valgrind --track-origins=yes ./errore" me tira dentro de la respuesta el error "error calling PR_SET_PTRACER, vgdb might block". Igual después sale el analisis de los leaks y los errores de memoria pero no se si puede estar influyendo ese error.

**Comment by CarloGauss33** [comment]
@PedroFuenzalida. El error es puramente de WSL,  pero no afecta a la ejecución de tu programa ni al funcionamiento de valgrind. asi que puedes ignorarlo.
