### ISSUE TITLE
mnt a ~

### ISSUE THREAD

**Issue by pablomaizag** [IIC2133-PUC/2021-2#42]
Hola! en mi terminal de vscode al abrir con wsl aparece: 
![image](https://user-images.githubusercontent.com/69779086/131775838-5f5d880b-5a23-4034-95f9-1d34c907a159.png)
Sin embargo, al parecer es mucho más eficiente el trabajar con ~ en vez de mnt debido a la lentitud que genera el segundo. No se como cambiarlo, me podrían ayudar :(?

**Comment by Huasito-Appel** [comment]
Hola Pablo, efectivamente funciona mejor si no estamos parados en el mount, basta con que cada vez que corras  ```wsl```en la terminal luego corras ``` cd ~``` . 
Por lo que creo en un inicio va a estar vacio, por lo que te recomiendo crear una carpeta , ```mkdir EDD ``` ,  donde guardes todo lo que vayas a utilizar del curso y que clones tu repo ahi adentro para trabajar.
Exito 😄
