### ISSUE TITLE
Calculo Complejidad de eventos

### ISSUE THREAD

**Issue by domingo2000** [IIC2133-PUC/2021-2#45]
Hola, me surgen dos al calcular la complejidad de cada evento. La primera tiene que ver con que hay varios eventos en los cuales los pasajeros de la fila premium se suben automáticamente (NUEVO PASAJERO, LLEGAR, SEPARAR, NUEVO TREN), por lo que ¿debo considerar la complejidad de dicha acción en todos lso eventos, o debo solamente considerar lo específico al evento?, por ejemplo en SEPARAR, calculo solo el hecho de que se separe el tren, o tambien debo contar con que luego del evento los trenes debel llegar y los pasajeros premium de la fila se deben subir. Eso me lleva a mi segunda duda, al mezclarse los eventos (Como cuando en LLEGAR se usa el evento ESTADO TREN) ¿debo considerar la complejidad total (onda que se bajan los pasajeros y que se imprima el estado del tren), o debo considerar solo lo específico a cada evento (ej: solo que se bajan los pasajeros)?.

**Comment by Huasito-Appel** [comment]
El informe apunta a que calcules la complejidad de los eventos que "vale la pena "    
Como mencionas existen eventos que no tienen mayor complejidad, basta que menciones en algun punto su existencia y por que podemos obviarlos del calculo final de la complejidad.
