### ISSUE TITLE
Duda evento Separar

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2133-PUC/2021-2#46]
En la descripción del evento Separar, no me quedó claro si luego de la separación del tren original en dos, los dos nuevos trenes por defecto tienen que llegar a sus destinos; es decir, si el evento Llegar se tiene que aplicar automáticamente a ambos trenes (primero el de vagones pares y luego el de impares) luego de ser separados durante el evento Separar.

Desde ya gracias.

**Comment by TrinidadVargas** [comment]
exacto, primero debes separar los trenes y luego deben llegar a los andenes indicados en el evento, cada tren que llega debe cumplir lo mismo que el evento llegar (imprimir LLEGAR seguido el estado del tren) . Tal vez te sirva ver el test easy 3 y su solución para ver exactamente el comportamiento

**Comment by JuanpaBC** [comment]
gracias!
