### ISSUE TITLE
Duda actualización de datos

### ISSUE THREAD

**Issue by ticastro** [IIC2133-PUC/2021-2#47]
Hola!

Realizando la tarea, llevo muchas horas trabado en como resolver un actualización de datos. 
Tengo las estructuras realizadas en forma de "cadena", donde hice una principal que almacene todas las estaciones, pudiendo acceder a ellas. Luego, las estaciones tienen sus andenes, los andenes a sus trenes (si es que corresponde), los trenes sus vagones, y cada vagon tiene sus asientos.

Estoy trabajando los vagones como listas ligadas, por lo cual cada vagon tiene como atributo al vagon siguiente, debido a que la cantidad de vagones no es un numero fijo. En el momento en que llega un pasajero, debo revisar la disponibilidad de asientos de un tren, donde luego almaceno el asiento y el vagon que tenga disponible, en caso de que lo esté. De aqui sale mi duda ya que, si un asiento esta disponible, tengo que acceder a tal vagón desde la estructura que almacena todo, pero no puedo acceder desde esta ya que no se puede hacer algo tipo "meta->estaciones[station_id]->anden[platform_id]->tren->primer_vagon" que luego haga una cantidad determinada de accesos de "meta->estaciones[station_id]->anden[platform_id]->tren->primer_vagon->siguiente_vagon->siguiente_vagon->siguiente_vagon". 

Le he dado muchas vueltas, pero no logro resolverlo. Cualquier tipo de ayuda se agradece.

**Comment by domingo2000** [comment]
En el fondo en la lista ligada basta que accedas al primer vagon usando lo que dijiste, ya con el puntero al primer vagon puedes recorrer la lista ligada puntero a puntero hasta que llegues al ultimo (que tiene NULL como valor siguiente), por lo que puedes usar un while o un for si es que cuentas la cantidad de carros que tiene un tren en alguna variable
