### ISSUE TITLE
Herencia en C

### ISSUE THREAD

**Issue by vicentevegaulloa** [IIC2133-PUC/2021-2#48]
Hola! Estoy desarrollando mis structs y si bien se que C es un lenguaje de bajo nivel, me preguntaba se existe una forma de hacer "herencia" entre structs para no repetir código. Por ahora solo estoy copiando funciones que comparten los structs.

**Comment by vicentevegaulloa** [comment]
Miento, no necesito herencia para lo que quiero hacer 😅 Pero igual me interesa saber 🤔

**Comment by CarloGauss33** [comment]
Hola @vicentevegaulloa, C no es un lenguaje orientado a objetos, por lo que no existen clases como tal ni herencia como tal (por defecto). Lo que si puedes hacer es extender una _struct_ haciendo que la definición de una contenga la otra

**Comment by vicentevegaulloa** [comment]
Perfecto, muchas gracias!
