### ISSUE TITLE
[Tarea 0] Duda cantidad de trenes por andén

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2133-PUC/2021-2#49]
Hola, quería corroborar si esta bien asumir que en un andén no puede haber más de un tren. Desde ya gracias.

**Comment by TrinidadVargas** [comment]
Hola, está respondido en la issue #16. Además, en el enunciado, en la parte de Input dice 
> todos los trenes tienen al menos 1 vagón y para el evento SEPARAR el tren tendrá al menos 2 vagones; siempre existirá un tren para el evento de SALIR; el andén de destino siempre se encontrará vacío.

**Comment by JuanpaBC** [comment]
gracias! y sorry por lo pavo
