### ISSUE TITLE
Evento  Separar

### ISSUE THREAD

**Issue by sebastianbreguel** [IIC2133-PUC/2021-2#51]
Hola!  en el evento de separar trenes, al momento de llegar  a sus  nuevos destinos los trenes desaparecen? o podrian ser usados despues de esto? y en caso de poder ser usado despues como se haria la asignacion del id correspondiente a cada nuevo tren?

**Comment by TrinidadVargas** [comment]
Hola! En el momento de separar los trenes, cada nuevo tren funciona exactamente igual que con el comando LLEGAR, por lo que no desaparecen y **sí** pueden volver a salir, subirse pasajeros etc. 

Sobre el id de cada tren, el enunciado dice
> para mantener consistencia con los identificadores, el tren que se dirige al destino-1 mantiene el id y el que se dirige al destino-2 crea un nuevo id.

El nuevo id es 1 unidad mayor al del último tren que se creó
