### ISSUE TITLE
Evento Separar

### ISSUE THREAD

**Issue by ticastro** [IIC2133-PUC/2021-2#52]
Hola!
Tengo una duda con el evento separar. Cuando ocurre este evento, el tren se divide en 2, siendo separados por la paridad del identificador que posean. Mi duda es acerca del identificador que tendrán los vagones una vez que se separe  el tren, ya que si los identificadores no cambian, estos nuevos trenes no podrían volver a separarse.
Gracias!

**Comment by TrinidadVargas** [comment]
Hola @ticastro 
Los vagones no necesariamente tienen identificador (puedes usar si se te hace más fácil la modelación) y se separan por la paridad de la **posición** del tren. Por esto, al separar un tren **sí** se puede volver a separar ya que nuevamente habrá un vagón de posición 0, 1 etc...
