### ISSUE TITLE
Tiempo de ejecución en hard test

### ISSUE THREAD

**Issue by jaimecoloma** [IIC2133-PUC/2021-2#53]
Hola! Respecto al tiempo de ejecución; estaba probando el test_0 hard y me da igual pero en tiempo de ejecución se demora más de 10 segundos :sob: . Puede ser que se deba a uso de la memoria general mientras lo ejecuto? Tengo igual varias aplicaciones abiertas y paginas de google, quería saber como funcionará el criterio de corrección en esos casos. No se cómo podría mejorar mi código para que sea más rapido :sweat_smile:, quizás es sólo mi computador

**Comment by CarloGauss33** [comment]
Hola @jaimecoloma, puedes utilizar el servidor #35 para revisar si los tiempos dan. En particular si tienes _printf_ estos aumentan mucho el tiempo de ejecucion. Otra cosa que puede aumentar mucho el tiempo de ejecucion es tener leaks o errores de memoria.

Igualmente, si superas 10 segundos, revisa tu codigo, puede ser que tengas lugares donde se realizan muchas iteraciones, o recursiones que revisen mas casos de los que deberían.

**Comment by jaimecoloma** [comment]
Yaa gracias! Voy a probarlo 😄
