### ISSUE TITLE
T0 complejidad del codigo

### ISSUE THREAD

**Issue by trinidadgatica** [IIC2133-PUC/2021-2#54]
Hola!,

En el enunciado se dice que se debe calcular el orden de complejidad en función de la cantidad de andenes, vagones y personas, trenes y asientos. Con esto, ¿a que se refiere?

**Comment by agustin-rios** [comment]
Hola Trini,

Una vez dispongas de un algoritmo que funciona correctamente, es necesario definir criterios para medir su rendimiento o comportamiento. Estos criterios se centran principalmente en su simplicidad y en el uso eficiente de los recursos (en tu caso la cantidad de andenes, vagones, personas, trenes y asientos). 

La razon de que se te pida el orden de complejidad de estos ultimos es porque tus funciones seran cada vez mas complejas y/o ineficientes segun la cantidad de que estos existan. Lo que tienes que hacer es justificar la complejidad de tus funciones y por ultimo de tu programa dependiendo de estos recursos y asi aprendas a manejar algoritmos eficientes (que es el objetivo de este curso).

En clases ya han visto como se calculan estos ordenes, un ejemplo reciente de ordenes de complejidad son:

![image](https://user-images.githubusercontent.com/48336498/132233163-d8cc567b-7bb1-4eb7-becb-661184f94eb5.png)

donde los ordenes de complejidad fueron calculados en funcion de la cantidad de datos a ordenar, y de la misma forma tendras que hacerlo para tus algoritmos en funcion de los recursos dados.

Espero que esto responda tu duda,

Saludos!

**Comment by Jamesmoreno21** [comment]
Hola! tengo dos dudas respecto a esto:
1. ¿Puedo hacer el cálculo de complejidad indicando sólamente lo que hace el algoritmo? o ¿hay que hacer algo para calcular la complejidad tipo Teorema Maestro?
2. El cálculo de complejidad, ¿es para complejidad de tiempo? o ¿también hay que considerar memoria? 

Gracias de antemano!
