### ISSUE TITLE
Evento Salir/Nuevo Tren

### ISSUE THREAD

**Issue by ian-fell** [IIC2133-PUC/2021-2#55]
Hola! 
Me surgió una duda respecto a la subida de los pasajeros al tren. Si en un andén no hay un tren disponible, y comienzan a llegar pasajeros tanto premium como normales, y luego se me pide crear un nuevo tren, al momento de crear el tren debo subir a todos los premium de una? O debo esperar al evento salir para que se suban? Me confunde el enunciado porque en la parte de NUEVO TREN no se nos pide subir a pasajeros que ya estén esperando, pero en el evento SALIR se asume que todos los pasajeros premium ya estaban a bordo, sin haberlos subido antes. ¿Cómo debería programar esta situación? ¿O puedo elegir yo?

**Comment by TrinidadVargas** [comment]
Hola! En el evento nuevo tren, si hay pasajeros premium en la fila se deben subir de inmediato (de otra forma no te darán todos los tests correctos)
