### ISSUE TITLE
Numeración asientos

### ISSUE THREAD

**Issue by nko205** [IIC2133-PUC/2021-2#57]
Hola, tengo una duda con la numeración de los asientos de cada tren. Esta es independiente en cada vagón ?? Ejemplo si tengo 2 vagones de capacidad 2 cada uno la numeración es | asiento1 asiento2 | asiento3 asiento4 | o | asiento1 asiento2 | asiento1 asiento2 | ??

**Comment by TrinidadVargas** [comment]
Hola, lo segundo | 0 1 2 | 0 1 | 0 1 2 3 |
