### ISSUE TITLE
Evento Desaparecer

### ISSUE THREAD

**Issue by IgnaciaJ** [IIC2133-PUC/2021-2#60]
Hola!! Para el evento desaparecer es necesario liberar la memoria altiro, o lo puedo hacer una vez finalizado el programa? gracias!!

**Comment by CrisBerriosL** [comment]
Lo que es importante es que tu código dé el output esperado y que lo haga de una manera eficiente cosa que no hayan timeout. Así que no es relevante cómo deciden manejar las cosas dentro del código mientras cumplan con eso. Obvio hay formas más óptimas que otras.
Teniendo eso en cuenta y aterrizando más a tu pregunta, depende de tí y de cada uno cómo decide manejar la memoria y los eventos dentro del código, no hay un requerimiento con eso. Puedes hacerlo como estimes conveniente, mientras se logre el output esperado y en el tiempo esperado.

Saludos!

**Comment by IgnaciaJ** [comment]
Gracias!!!
