### ISSUE TITLE
Evento Remover: Pasajeros premium en el anden.

### ISSUE THREAD

**Issue by DomingoCarvajal** [IIC2133-PUC/2021-2#61]
Hola! 

Si un tren está lleno en una estación, lo que podría significar que hay pasajeros premium en el andén. En este situación, si ese tren remueve un pasajero ilegal, el premium que está en el andén se tiene que subir de inmediato al tren?

**Comment by TrinidadVargas** [comment]
exacto, un pasajero premium se sube inmediatamente cuando hay un asiento disponible

**Comment by DomingoCarvajal** [comment]
Gracias!
