### ISSUE TITLE
Complejidad Estado Tren

### ISSUE THREAD

**Issue by DomingoCarvajal** [IIC2133-PUC/2021-2#68]
Hola para los eventos llegar, desaparecer y separar hay que considerar la función de ESTADO TREN?o hay que calcularla sin ESTADO TREN y uego calcular la complejidad de ESTADO TREN por si sola? No me queda claro.

Gracias de antemano.

**Comment by Huasito-Appel** [comment]
No existe una forma particular, puedes explicar la de Estado Tren por si sola y luego referenciarla en todas estas si te acomoda mas.
Te recomiendo ver esta issue https://github.com/IIC2133-PUC/2021-2/issues/69
Me avisas si quedan dudas, Exito!
