### ISSUE TITLE
Error con #include

### ISSUE THREAD

**Issue by En-clases** [IIC2133-PUC/2021-2#70]
Hola, he estado arreglando mi código para que funcione más rápido y encontré que tenía este problema:
![image](https://user-images.githubusercontent.com/69520590/132903707-cb076c99-b1c3-4d8a-b024-6fcee1877630.png)

Aparentemente esto no me deja utilizar la variable ``output_file`` (que viene con el archivo de la tarea) para poder escribir en el archivo ``out.txt``. Debido a esto debo abrir y cerrar el archivo ``out.txt`` cada vez que debo escribir algo, lo que hace muy ineficiente el programa (todos los test hard me demoran más de un minuto incluso después de haber quitado loops innecesarios).
Espero me puedan ayudar a tiempo :c, gracias.

**Comment by tlagosh** [comment]
Me pasa lo mismo!

**Comment by Huasito-Appel** [comment]
En particular se soluciono esto, pero ocurre por que no tienen instaladas las librerias, ahi cleme estaba parado en OneDrive.
Como recomendacion para los que aun no lo hacen en windows hagan lo siguiente.
- Abrir terminal
- wsl en consola , esto te abre tu particion de linux instalada
- cd ~, te lleva al "escritorio" de tu particion
- cd "carpeta del ramo"
Es ideal trabajar directo desde el home y no sobre el mount, por temas de velocidad ( puede pasar que en el mount se les demore mas correr )  y que aveces pasan cosas raras. Entonces para el resto de tares ( u cosas que deban hacer en C) corranlo de esta forma.
