### ISSUE TITLE
Preguntas I1

### ISSUE THREAD

**Issue by agustin-rios** [IIC2133-PUC/2021-2#74]
Primera Sesion de Dudas: 14:00hrs
Segunda Sesion de Dudas: 19:30hrs
Tercera Sesion de Dudas: 21:30hrs
https://zoom.us/j/96158709209

## Preguntas Generales
Si no respondo una pregunta, no entrego en siding?
> La pregunta que no respondas, se debe dejar sin responder en siding

 El desarrollo se puede hacer a mano y después subirlo escaneado?
> La prueba puede ser hecha a mano y luego escaneada, también pueden usar otros formatos mientras sea entregada en formato .pdf . Lo importante es que debe estar firmada por ti.

La prueba debe ser entregada con algún nombre especial?
> No se necesita un nombre de archivo específico.

Entonces una vez que se comienza hay plazo hasta las 23:59?
> Sí.

Se pueden revisar los apuntes de clases y propios?
> Sí.

## Pregunta 1
Nota: El enunciado fue actualizado, por lo tanto revisar el enunciado si es que existen dudas

¿Que significa el simbolo que rodea a n/3?
> Parte entera

¿A[1] es el segundo elemento? o comienzan desde el 1 los índices?
> Si, es el primer elemento

A[1,b] ese array significa los elementos de A desde 1 a b o solo un array de 2 elementos (el 1 y el b)
> Si, es una forma de incluir todos los elementos entre 1 y b, incluyéndolos

¿A([a,n], tiene largo n-a?
> n-a+1

¿En la 1a hay dos llamados iguales entonces?
> Da la impresión de ser iguales, pero en la práctica no son exactamente iguales.

Al aplicar la recursión en QuicoSort[a,n], para aplicar la regla de QuicoSort de n<= 1, es en verdad n<= a? Ósea, como que corremos todos los valores en a?
> Si n ≤ 1 entonces ya esta ordenado

¿Como es el array de input a la funcion?
> Es cualquier array, donde i y f son el "slice" del subarray a ordenar.
## Pregunta 2

Cuando dice que las operaciones se realizan en tiempo constante se refiere a O(1)?
> Si

hay que hacer un pseudocódigo?
> No debería ser necesario, puedes usarlo pero no sería explicarlo

La nueva versión de insertionSort tiene que seguir los mismos pasos de la versión que conocemos o podemos agregar pasos extra?
> En principio los mismos pasos

¿Podemos hacer uso de algun otro algoritmo usado en clases?
> Tiene que ser una modificacion al insertionSort visto en clases

¿En que caso tiene que ser el O(nLog(n))?
> En el peor caso

Puedo retornar una magicList
> Si

¿Puedo asumir que se el largo de MagicList de antemano? O asumir que haber llegado al final de la MagicList toma O(1)?
> Si, pueden asumirlo

Es nescesario eliminar el elemento de A, o puedo ocupar una forma que no requiera eliminarlo
> No hace mucha diferencia, pero si se podria

## Pregunta 3

¿Bajo que criterio se ordenan los pasajeros?
> Los pasajeros con id mas chicos, van primeros. Por lo que los "asientos están fijos". Por lo tanto hay que reordenar a los pasajeros para que aquellos con id menor queden antes que aquellos de id mayor

¿los asientos están en vagones que no corresponden?
> Los asientos están desordenados dentro de los vagones.

en la 3b es llegar a la complejidad que ya sabemos de la 3a?
> en la 3a hay dos cosas diferentes, luego hay que calcular la complejidad del algoritmo completo en la b.

¿La idea es que el algoritmo total de ordenación (para asientos y vagones) sea de  O(nlogn) en el peor de los casos? O que solo para ordenar los vagones sea de ese tiempo?	
> O(nlogn) es **solo** para la ordenación de los vagones.

¿Qué se desordena, y qué tenemos que ordenar?
> Los asientos dentro de cada vagón, y los vagones entre ellos.

¿Entonces, la complejidad de mi algoritmo puede ser mas de O(nlogn)?
> Si, siempre y cuando ordenes en dicho tiempo la lista ligada

¿Los Id de pasajeros y asientos son por Vagon?
> Si

## Pregunta 4
QuickerSort retorna la lista ordenada?
> Si

Cómo funciona el quickerSort?
> Es una generalización del quicksort que vimos en clase, por lo que toma ese algoritmo y en vez de un pivote utiliza dos.

¿Podemos asumir que no hay elementos repetidos en el arreglo ordenado?
> En la versión nueva del enunciado se aclara que todos los elementos son distintos.

**Comment by etoteiza** [comment]
En la pregunta 2, se debe calcular explícitamente la complejidad O(n logn)?

**Comment by JuaniAndres** [comment]
Hola, para la pregunta 4 partes c,d es necesario calcular la complejidad al igual que la parte a,b o solo basta con explicar porque son el mejor y peor caso?

**Comment by festelle** [comment]
En la pregunta 3b, hay que calcular solo la complejidad de tiempo? o también de memoria?  Y la complejidad solo en el peor caso o también en el mejor y promedio?

**Comment by bmorrisc** [comment]
Para las preguntas 2 y 3, si usamos un algoritmo de complejidad conocida (visto en clases) es necesario demostrar qué complejidad tiene haciendo el cálculo o se puede asumir?

**Comment by CarloGauss33** [comment]
> En la pregunta 2, se debe calcular explícitamente la complejidad O(n logn) o basta señalar los cambios al insertionsort?

La idea es que digas cuales son los cambios, aunque eso no asegura que el algoritmo sea O(nlogn), por lo que deberias ademas de señalar los cambios deberias mostrar dicha complejidad

**Comment by CarloGauss33** [comment]
> Hola, para la pregunta 4 partes c,d es necesario calcular la complejidad al igual que la parte a,b o solo basta con explicar porque son el mejor y peor caso?

Basta con mencionar  y explicar el caso, ademas de dar las razones de porque es asi.

**Comment by CarloGauss33** [comment]
> En la pregunta 3b, hay que calcular solo la complejidad de tiempo? o también de memoria? Y la complejidad solo en el peor caso o también en el mejor y promedio?

Complejidad de tiempo en el Mejor y Peor Caso

**Comment by CarloGauss33** [comment]
> Para las preguntas 2 y 3, si usamos un algoritmo de complejidad conocida (visto en clases) es necesario demostrar qué complejidad tiene haciendo el cálculo o se puede asumir?

Puedes asumirlo, pero idealmente menciona "Tal como se vio en clases, este algoritmo tiene complejidad X"

**Comment by vicentevegaulloa** [comment]
Para la pregunta 3b, como piden explicar detalladamente lo que haríamos en un lenguaje como C, al trabajar con listas ligadas tengo que explicar como haría un append paso a paso o puedo simplemente "llamar" al append asumiendo que ya está definido?

**Comment by jiurrutia** [comment]
Hola, en la pregunta 1.b es necesario describir cual seria el peor caso? o basta con mostrar la complejidad?

**Comment by jitorralba** [comment]
Hola, para el calculo de complejidad en la 3b es válido asumir que todos los vagones tienen la misma cantidad de asientos?

**Comment by CarloGauss33** [comment]
> Para la pregunta 3b, como piden explicar detalladamente lo que haríamos en un lenguaje como C, al trabajar con listas ligadas tengo que explicar como haría un append paso a paso o puedo simplemente "llamar" al append asumiendo que ya está definido?

Hola, es solo una recomendacion. Puedes perfectamente solo describir el algoritmo con pseudocodigo

**Comment by CarloGauss33** [comment]
> Hola, en la pregunta 1.b es necesario describir cual seria el peor caso? o basta con mostrar la complejidad?

Para mostrar la complejidad del peor caso debes indicar como es dicho caso. Basta con explicarlo de forma general

**Comment by CarloGauss33** [comment]
> Hola, para el calculo de complejidad en la 3b es válido asumir que todos los vagones tienen la misma cantidad de asientos?

si

**Comment by etoteiza** [comment]
Hola! Si encontré información en una página, puedo usar eso y referenciarlo?

**Comment by CarloGauss33** [comment]
> Hola! Si encontré información en una página, puedo usar eso y referenciarlo?

Hola, si puedes.
