### ISSUE TITLE
Pregunta materia ABB: sobre algoritmo insert(A, k)

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2133-PUC/2021-2#79]
Hola, en la sgte diapo me confunde la línea "B<-search(A,k)", porque entendí que search(A,k) devuelve vacío si k no existe, y entonces B quedaría definido como vacío, pero no me hace sentido eso. Asumo que debo estar interpretando algo mal y agradezco cualquier ayuda. Adjunto foto de la diapo:
![image](https://user-images.githubusercontent.com/80859173/134942867-d3e4c2bf-5a03-47df-a118-c43e70ed0492.png)

**Comment by CarloGauss33** [comment]
@JuanpaBC, Es correcto que queda vacío. Dado que lo que realiza insert es primero revisar si la _key_ ya existe y si existe retorna dicho nodo (para evitar duplicados). Segundo En caso de que no exista ahi pasa al resto del algoritmo y crea un nodo, lo conecta y le asigna la Key.

Avisame si esto resuelve tu duda

**Comment by JuanpaBC** [comment]
Ah ya perfecto ahora me queda claro muchas gracias!
