### ISSUE TITLE
[Tarea 1] Definición de Component Tree

### ISSUE THREAD

**Issue by domingo2000** [IIC2133-PUC/2021-2#80]
Hola, me surge una duda con la tarea respecto a la definción de Component-Tree (O Max-Tree). Puesto que en enunciado dice que los nodos que son iguales a su padre son omitidos, mientras que en uno de los papers no los omite, adjunto imagenes
Enunciado:
![image](https://user-images.githubusercontent.com/40220174/134963975-8f3e6c6e-c4a0-4d7f-83fa-3568ea4023cb.png)
En este caso es omitido el nodo con el pixel "21" en la altura 1 del arbol.
Paper "Interactive Segmentation Based in Component Trees":
![image](https://user-images.githubusercontent.com/40220174/134964074-66e3481d-3ade-4292-9271-7f60166d09a7.png)
En este caso los nodos son repetidos nivel a nivel (Nodos C, G, L, Q).
Por otro lado en el paper del algoritmo de Salembier definen el component Tree como que cada nodo contiene los pixeles con las componentes de manera recursiva, es decir el padre contiene el fondo, no el fondo y sus pixeles interiores:
![image](https://user-images.githubusercontent.com/40220174/134964302-3c0b09f8-3539-457f-aee1-6d6451ddfd89.png)
Ahí el hijo de "A" contiene a "BDF", y no a "BCDEF" como vendría siendo según las otras dos definiciones, a raíz de esto no se con cual definición quedarme, ni que modelación de component tree se debe usar efectivamente para el alpha filter de manera óptima.

**Comment by nvaldiviesoo** [comment]
Hola! 
Me llamó la atención lo mismo. Para el primer paper que mencionas, en la descripción del component-tree se muestra
![Captura de Pantalla 2021-09-28 a la(s) 21 24 03](https://user-images.githubusercontent.com/69522408/135182794-05874ba6-4c36-4e82-96e5-3bf17e04b312.png)
Entiendo así que se trata de un subconjunto propio (estricto), porque más adelante los autores usan el símbolo ⊆ para denotar subconjuntos impropios. Según lo veo, ello condice el enunciado de la tarea, pero no hace sentido con el diagrama que muestran en el paper. Por ejemplo, según el diagrama de la _Figure 1_ se tiene que C es un ancestro de G, pero C⊄G, ya que C=G (lo que contradice el punto mencionado).
Agradezco también si pueden aclararlo.

**Comment by andres-tamm** [comment]
Hola! No soy ayudante pero creo que entiendo tu duda.

La definición del enunciado no es la misma que está en ninguno de los dos papers. Es necesario notar que en  "Interactive Segmentation Based in Component Trees" los nodos G y L son idénticos a C, por lo tanto en nuestro caso esos nodos se omiten y en la rama central del árbol deberíamos tener algo como A -> C -> Q.  (Pasa algo similar con el nodo H y el nodo K, también deberían ser omitidos)

En el caso del algoritmo de Salembier, lo que hace es ir sacando los pixeles de los nodos padre para dejarlos en el nodo hijo a medida que va avanzando en el árbol, para nuestro enunciado esto no hay que hacerlo y lo que se pide es mantener todos los píxeles en el nodo padre y también agrupar esos pixeles en el nodo hijo. De todas formas el algoritmo de Salembier es útil para notar que los nodos idénticos no se consideran, solo que para Salembier los nodos idénticos quedan "vacíos" dado que a medida que avanza va cambiando los píxeles de nodo y en el caso de que el siguiente nivel, el nodo sea igual al anterior significa que el padre quedó vacío y por lo tanto se elimina.

Con respecto a usar el alpha filter de manera óptima, creo que no va a depender de la implementación del árbol dado que debemos seguir el formato explicitado en el enunciado.

Ojalá te sirva, saludos!

Pd: Reitero que no soy ayudante y de todas formas esperaría la respuesta de uno de ellos, esto es mas bien lo que yo entendi del enunciado.
