### ISSUE TITLE
Problemas con librería libpng

### ISSUE THREAD

**Issue by EstebanReyes1998** [IIC2133-PUC/2021-2#82]
Actualmente estoy utillizando WSL y VSCode con una extensión de C para realizar mi tarea. 
Sin embargo, apenas corriendo el código base me tira un Segmentation Fault. Adjunto imagenes
![image](https://user-images.githubusercontent.com/42703907/135524373-7efd7cbf-4e4e-40b1-924d-d995d8c1c9c6.png)
Sale esto en VSCode
![image](https://user-images.githubusercontent.com/42703907/135524431-bf27542e-dba3-4823-97b6-2e178e530257.png)
He buscado en internet pero no he encontrado nada. No debo ser el único con este problema verdad?
Gracias de antemano
(Y si, ya instale la librería de forma exitosa)
![image](https://user-images.githubusercontent.com/42703907/135524656-95159d1a-a41a-46a0-a496-b6d509689f73.png)

Edit: Al analizar el error en valgrind se aprecia esto:
![image](https://user-images.githubusercontent.com/42703907/135663064-82a3a362-8be1-4222-8919-25ccd78c3d82.png)

**Comment by ftobar22** [comment]
me pasa lo mismo en Mac :(

**Comment by Huasito-Appel** [comment]
Hola Esteban, instalaste la libreria como se menciona en el README ?, puede ser eso. 
PD escribe en discord en caso contrario para que la ayuda sea mas fluida.

**Comment by EstebanReyes1998** [comment]
> Hola Esteban, instalaste la libreria como se menciona en el README ?, puede ser eso. PD escribe en discord en caso contrario para que la ayuda sea mas fluida.

Ya había anexado una imagen al respecto pero subo otra igual
![image](https://user-images.githubusercontent.com/42703907/135773796-affaf688-9f9b-48c7-b182-5b721bf8cbd9.png)
Donde encuentro el link del discord?

**Comment by ftobar22** [comment]
> me pasa lo mismo en Mac :(

Para los que quieran correr todo sin **Docker** o **VMs** en MacBooks M1 vean [este post](https://apple.stackexchange.com/questions/414622/installing-a-c-c-library-with-homebrew-on-m1-macs), todo se arregla con un par de variables de entorno.
