### ISSUE TITLE
Segmentation Based on Component-tree

### ISSUE THREAD

**Issue by PedroFuenzalida** [IIC2133-PUC/2021-2#84]
Hola! Que es lo que se está minimizando en esta expresión?

![_Interactive Segmentation Based on Component-trees y 6 páginas más - Personal_ Microsoft​ Edge 02-10-2021 16_23_54 (2)](https://user-images.githubusercontent.com/69521483/135729693-2c9d0243-146d-41eb-877f-919d8401bf72.png)

**Comment by domingo2000** [comment]
No soy ayudante pero yo lo entendí de esta manera: Tienes tu arbol de component tree con muchisimos nodos con las diferentes vecindades, luego imagina todas las combinaciones de vecindades "pegadas", eso es 
![image](https://user-images.githubusercontent.com/40220174/135731314-787c7293-2519-4903-961f-95528122cc19.png)
Luego la funcion d^{alpha} calcula un grado de error entre el marker dado y la imagen con esas vecindades pegadas. Por lo que lo que se quiere minimizar es ese "error". Con eso logras dar como salida una imagen que tome de la mejor manera posible el marcador dado. Es como la herramienta de selección de photoshop, que te va agarrando justo lo que vas seleccionando basado en los colores, esto es parecido pero con escalas de grises.

**Comment by JDomingoSilva** [comment]
pero están tomando el mín de K, osea estan reduciendo el conjunto de vecindades. Yo lo entendí como minimizar la cantidad de vecindades de la foto original que son necesarias para recrear el marker, bajo un margen de error dado.
