### ISSUE TITLE
[Tarea 1] Recomendación de como debuguear la tarea

### ISSUE THREAD

**Issue by domingo2000** [IIC2133-PUC/2021-2#85]
Hola, resulta que comenzé a sacar outputs de imágenes en la tarea y están extremadamente parecidos a los test dados, pero no iguales 😢 y no se bien por donde partir buscando, pues a mis outputs solo le falta agregar algunos nodos del component tree a la imagen (Adjunto foto). 

Este es mi ouput:
![out](https://user-images.githubusercontent.com/40220174/135731479-08217706-99d1-46f3-bf02-d7bc8ad19bb2.png)

)
Este es el output que debería ser:
![campus](https://user-images.githubusercontent.com/40220174/135731459-ff4365db-b25a-40cf-a955-e7a2b0f47b95.png)

Si se notan bien hay algunos pixeles blancos que no salen en la parte de abajo del cristo en mi output, por otro lado en el de la cara si hay más diferencia.
Out propio:
![out](https://user-images.githubusercontent.com/40220174/135731538-9f456539-2d92-4d54-8dcf-22a1c69faa12.png)
Out esperado:
![outCara](https://user-images.githubusercontent.com/40220174/135731514-9a6633ad-ac7f-4eb3-9793-7243231e6c75.png)

Agradecería mucho que me den ideas 😅

**Comment by Huasito-Appel** [comment]
Hola Domingo, primero congrats en ya estar sacando imagenes, para el tema del debuggeo parte si o si por las imagenes mas pequeñas ( A.K.A los test easy ), si esos te andan igual pasa a los medianos, pq en estas imagenes tan grandes es facil perderse.
Otra forma de verlo es hacerce un script pequeño que imprima el arbol, cosa de ir viendo que nodos tenemos diferentes y cual puede ser la causa.
Finally, debuggear estas tareas es complejo, intenta ir a discord y encontrarnos a alguno con harto tiempo para ver tu codigo en detalle y encontrar que puede estar pasando.

**Comment by domingo2000** [comment]
Y existe alguna posibilidad de que suban algunos test de los valores de ps y n de los nodos al hacer el filtro alpha?? Que he estado escribiendo varios tests unitarios para probar el arbol y creo que no va por ahí, pero no se como debuggear el filtro si no tengo algún test.

**Comment by domingo2000** [comment]
Logré encontrar un error, pero ahora tengo uno nuevo 😞 . Pero, pero esta vez me llama la atención el output que sale del test de los que pasaron. En el test de la planta por ejemplo, el marcador toma casi toda la hoja de la planta, y aún así devuelve solo algunos pixeles. Printeando y calculando a mano una parte del árbol, tampoco hace sentido que ciertas vecindades se excluyan del output, por ejemplo, tengo este nodo:
![image](https://user-images.githubusercontent.com/40220174/135801126-9e454dfc-28f2-4621-b4e4-bfb378dab0ea.png)
El cual si lo comparamos con el marker dado
![image](https://user-images.githubusercontent.com/40220174/135801200-9cba07fb-c888-4c57-ac7f-0d27c4567c15.png)
Me da que el ps(N,G) y n(N,G) estén bien, y se quede finalmente con el caso 1 de la función recursiva, es decir se queda con ese nodo, por lo que no podría ser que saque el output del test que dieron, pues para ello tendría que haber caido en el caso recursivo.
Agradecería si pudieran subir un poco más que solo input output, pues estoy sacando idénticos algunos test (Como el del cerebro y eyeleash) pero aún así hay pequeñas diferencias de 1 o 2 vecindades con otros test. (Y como la nota es binaria entonces castiga bastante 😢 ).

**Comment by maureenmaremaa** [comment]
Hola! Yo estoy teniendo el mismo problema que Domingo. Me salen correctos varios test, por ejemplo, river, sans, eyeleash, brain pero la planta me dice que está incorrecto. Viendo el marker no me hace sentido el output esperando. Adjunto una foto de mi output de plant, por si alguien sabe lo que puede estar pasando. 

Muchas gracias de antemano!
![Screen Shot 2021-10-04 at 17 51 30](https://user-images.githubusercontent.com/48293523/135929990-efe33121-3dd1-4582-b0f1-1ceb42110b4a.png)
!

**Comment by Huasito-Appel** [comment]
Si!  Tenemos que ver el detalle del codigo, la pauta la volvimos a revisar y se ve bien, tenemos que revisar en detalle su codigo para que que falla, Porque no tenemos claro si es un tema del filtro o de su arbol, por ejemplo si ustedes corren la mona lisa con 0.25 les sale bien, si corremos la pauta en el test de la planta con 0.01 da el resultado que ustedes muestran.   
Subiremos en breve un anuncio al respecto, pero en resumen daremos puntajes parciales con respecto a la similitud del output esperado, cosa de que puedan optar al puntaje completo si cumplan un umbral que determinaremos.
