### ISSUE TITLE
[Tarea 1] Filtrar Component Tree

### ISSUE THREAD

**Issue by TamaraErdmann** [IIC2133-PUC/2021-2#88]
Hola!
He leído mucha documentación de los Component Trees y no logro entender cómo se obtiene la imagen filtrada a partir de un alpha. Más allá de la estructura del árbol, no me queda claro cómo se seleccionan los nodos a retornar en la imagen del output y cómo estos deben cambiar su escala de grises. Agradecería muchísimo si nos ayudan un poco con eso :)
Gracias!

**Comment by nachobascar** [comment]
Hola!
El component tree es solo una estructura que facilita el uso del filtro, pero no es el filtro en sí. Para ver las condiciones del filtro y como seleccionar los nodos debes leer el paper que adjuntamos en el enunciado:

https://www.ipol.im/pub/art/2014/71/article.pdf

La idea es que logres utilizar el component tree para realizar este filtro de una forma eficiente.
Saludos!!
