### ISSUE TITLE
[Tarea 1] Omitir nodos

### ISSUE THREAD

**Issue by Coolgatty** [IIC2133-PUC/2021-2#89]
Hola con respecto a la parte del enunciado que dice 

`Se omite un nodo si este guarda los mismos pı́xeles que su padre. Esto ocurre por ejemplo, si un
vecindario descendiente del nodo P estuviese conformado solo por pı́xeles con un grisáceo mayor o
igual a U + 2. En ese caso, se omitirı́a el nodo con umbral U + 1 y el nodo P se asociarı́a directamente
al nodo c
![p](https://user-images.githubusercontent.com/3936616/135904532-5fad25fd-10fb-48b0-94fd-e6b9542a6e91.png)
on un umbral igual a U + 2.`

Yo entiendo que si hay vecindarios como en esta imagen: ![p](https://user-images.githubusercontent.com/3936616/135904532-5fad25fd-10fb-48b0-94fd-e6b9542a6e91.png)
 
Si el umbral del gris claro tiene mas de 1 umbral de diferencia con el umbral del gris oscuro entonces el umbral del gris oscuro solo incluira 2 vecindarios y no los de gris claro pues en esos vecindarios no hay pixeles con valor == u + 1.

Estoy en lo correcto?

**Comment by nachobascar** [comment]
Hola! No sé si entendí bien tu pregunta, pero en la imagen que pones, si tomas en cuenta desde el negro, habría un vecindario con todos los pixeles. Luego, tendrías que tomar en cuenta desde el gris oscuro (porque no hay otros grises entre medio), e incluirías dos vecindarios más (los dos grises oscuros), y finalmente llegarías al gris claro donde incluirías los siguientes 3 vecindarios de los grises claros.

Lo importante es no incluir los vecindarios de los grises claros más de una vez, ya que técnicamente al revisar en el umbral del gris oscuro, los grises claros también serían vecindarios, pero se repetirían al subir los umbrales.

Me avisas si esto no resuelve tu duda
