### ISSUE TITLE
[Tarea 1] Duda con node_at_level en el pseudo-codigo 

### ISSUE THREAD

**Issue by maggiemunoz** [IIC2133-PUC/2021-2#90]
Hola! Estaba revisando el pseudo código de uno de los pdfs que nos enviaron (adjunto imagen) y en la linea que marque sale que decimos que node_at_level(p) es ahora True, pero no debería ser node_at_level(q)? Considerando que estamos revisando los vecinos, conceptualmente tiene más sentido decir que si encuentro un vecino que no he revisado, es porque hay un nodo en el nivel de ese vecino. Además, mi código no retornaba el árbol correcto hasta que cambie la p por la q. Mi duda es si efectivamente el pdf tiene un error o si es un caso de que llegue al resultado correcto de la forma equivocada jajaja, muchas gracias!

<img width="400" alt="Captura de Pantalla 2021-10-04 a la(s) 18 19 48" src="https://user-images.githubusercontent.com/62019819/135926337-4154debd-6964-46d3-9cfa-8e9c8a68521e.png">

**Comment by nachobascar** [comment]
Hola! El paper está correcto, lo que pasa es que es necesario que se señale que hay un nodo abierto en el nivel del pixel padre antes de comenzar la recursión con el vecino ( Ojo que el que "q" sea vecino significa que es de un umbral mayor o igual a "p"), así para poder encontrar luego al nodo padre en la recursión.
